/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Frame: KL_7.java
 * Fungsi: Tambah laporan kendala oleh kontraktor
 * Auto ID format: L0001
 * Laporan otomatis terhubung dengan proyek kontraktor login
 * Setelah tambah, langsung tampil di Menampilkan_Laporan dengan highlight hijau pastel
 * @author hp
 */
public class KL_7 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KL_7.class.getName());
    private String loggedInUsername;

    public KL_7() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public KL_7(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        System.out.println("DEBUG: Kontraktor di KL_7 = " + loggedInUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Deskripsi");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 200, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Jenis Kendala");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 200, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal (yyyy-mm-dd)");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, -1));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TAMBAH LAPORAN ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 550, 50));

        jButton5.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 0, 0));
        jButton5.setText("Kirim");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 83, -1));

        jButton4.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("Kembali");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 83, -1));

        jTextField9.setBackground(new java.awt.Color(0, 0, 102));
        jTextField9.setForeground(new java.awt.Color(255, 255, 255));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, 200, 30));

        jTextField7.setBackground(new java.awt.Color(0, 0, 102));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 200, 30));

        jFormattedTextField3.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, 460));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setText("Jumlah ");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jFormattedTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Tombol "Kembali"
        Kelola_Laporan laporanFrame = new Kelola_Laporan(loggedInUsername);
        laporanFrame.setLocationRelativeTo(null);
        laporanFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // Tombol "Kirim" → INSERT laporan baru
        String tanggal = jFormattedTextField3.getText().trim();
        String jenis = jTextField9.getText().trim();
        String deskripsi = jTextField7.getText().trim();

        // ✅ Status default
        String status = "Menunggu Verifikasi Admin";

        if (tanggal.isEmpty() || jenis.isEmpty() || deskripsi.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Tanggal, Jenis Kendala, dan Deskripsi wajib diisi!",
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = db_connection.getConnection()) {
            // Ambil proyek kontraktor
            String getProyekId = "SELECT Proyek_id_proyek FROM pengguna WHERE username = ?";
            PreparedStatement stmt1 = conn.prepareStatement(getProyekId);
            stmt1.setString(1, loggedInUsername);
            ResultSet rs = stmt1.executeQuery();

            if (rs.next()) {
                String proyekId = rs.getString("Proyek_id_proyek");

                // ✅ Generate ID laporan baru format 5 digit (contoh: L0001, L0012)
                String getLastId = "SELECT id_laporan FROM laporan ORDER BY id_laporan DESC LIMIT 1";
                Statement stmt2 = conn.createStatement();
                ResultSet rs2 = stmt2.executeQuery(getLastId);
                String newId = "L0001";
                if (rs2.next()) {
                    String lastId = rs2.getString("id_laporan");
                    int num = Integer.parseInt(lastId.substring(1)) + 1;
                    newId = String.format("L%04d", num); // 👈 4 angka setelah huruf L
                }

                // ✅ Insert laporan baru
                String insert = """
                    INSERT INTO laporan (id_laporan, tanggal_laporan, jenis_kendala, deskripsi, status_tindak_lanjut, Proyek_id_proyek)
                    VALUES (?, ?, ?, ?, ?, ?);
                """;
                PreparedStatement stmtInsert = conn.prepareStatement(insert);
                stmtInsert.setString(1, newId);
                stmtInsert.setDate(2, Date.valueOf(tanggal));
                stmtInsert.setString(3, jenis);
                stmtInsert.setString(4, deskripsi);
                stmtInsert.setString(5, status);
                stmtInsert.setString(6, proyekId);

                int rows = stmtInsert.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this,
                        "✅ Laporan berhasil dikirim.\nStatus awal otomatis: " + status + ".",
                        "Sukses", JOptionPane.INFORMATION_MESSAGE);

                    // ✅ Setelah berhasil tambah laporan → buka Menampilkan_Laporan dan highlight ID baru
                    Menampilkan_Laporan tampilFrame = new Menampilkan_Laporan(loggedInUsername, newId);
                    tampilFrame.setLocationRelativeTo(null);
                    tampilFrame.setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menambah laporan.",
                        "Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Proyek kontraktor tidak ditemukan!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                "Kesalahan database: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this,
                "Format tanggal harus yyyy-mm-dd!",
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new KL_7().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
