/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Frame: KP_1.java
 * Fungsi: Update proyek yang dikerjakan kontraktor login
 * @author hp
 */
public class KP_1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KP_1.class.getName());

    // ✅ Simpan username kontraktor yang login
    private String loggedInUsername;

    /**
     * Konstruktor default (untuk preview NetBeans)
     */
    public KP_1() {
        initComponents();
        setLocationRelativeTo(null);
        setupComboBox();
    }

    /**
     * ✅ Konstruktor tambahan (dipakai dari Kelola_Proyek)
     */
    public KP_1(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        setupComboBox();
        System.out.println("DEBUG: Kontraktor di KP_1 = " + loggedInUsername);
    }

    /**
     * ✅ Isi combo box status proyek
     */
    private void setupComboBox() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Tahap Perancangan");
        jComboBox1.addItem("Sedang Dikerjakan");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel7.setText("Lokasi");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 200, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setText("Tanggal Selesai (yyyy-mm-dd)");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 230, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal Mulai (yyyy-mm-dd)");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 230, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setText("Anggaran");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 190, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Status");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 350, 190, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Nama Proyek");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, -1));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UPDATE PROYEK");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 340, 60));

        jButton2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 83, -1));

        jButton1.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Kirim");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 83, -1));

        jFormattedTextField3.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jFormattedTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 230, 30));

        jFormattedTextField2.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 190, 30));

        jFormattedTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 230, 30));

        jTextField4.setBackground(new java.awt.Color(0, 0, 102));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 200, 30));

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 200, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 799, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField1ActionPerformed

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // ✅ Tombol "Kembali"                                       
        Kelola_Proyek proyekFrame = new Kelola_Proyek(loggedInUsername);
        proyekFrame.setLocationRelativeTo(null);
        proyekFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            // ✅ Tombol "Kirim" → Update proyek milik kontraktor                                        
        String nama = jTextField1.getText().trim();
        String lokasi = jTextField4.getText().trim();
        String tanggalMulai = jFormattedTextField1.getText().trim();
        String tanggalSelesai = jFormattedTextField3.getText().trim();
        String anggaranStr = jFormattedTextField2.getText().trim();
        String status = (String) jComboBox1.getSelectedItem();

        if (nama.isEmpty() || lokasi.isEmpty() || tanggalMulai.isEmpty() || tanggalSelesai.isEmpty() 
                || anggaranStr.isEmpty() || status == null) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", 
                    "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
        java.time.LocalDate mulaiDate, selesaiDate;

        try {
            mulaiDate = java.time.LocalDate.parse(tanggalMulai, formatter);
            selesaiDate = java.time.LocalDate.parse(tanggalSelesai, formatter);
        } catch (java.time.format.DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, 
                "Format tanggal harus yyyy-mm-dd dan tanggalnya valid!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (selesaiDate.isBefore(mulaiDate)) {
            JOptionPane.showMessageDialog(this, 
                "Tanggal selesai tidak boleh lebih awal dari tanggal mulai!", 
                "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Connection conn = db_connection.getConnection()) {
            // 🔹 Ambil ID proyek dari kontraktor login
            String getProjectId = "SELECT Proyek_id_proyek FROM pengguna WHERE username = ?";
            PreparedStatement ps1 = conn.prepareStatement(getProjectId);
            ps1.setString(1, loggedInUsername);
            ResultSet rs = ps1.executeQuery();

            if (!rs.next() || rs.getString("Proyek_id_proyek") == null) {
                JOptionPane.showMessageDialog(this, 
                    "Kontraktor belum memiliki proyek yang terhubung!", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String idProyek = rs.getString("Proyek_id_proyek");

            // 🔹 Update proyek berdasarkan ID itu
            String updateSQL = """
                UPDATE proyek
                SET nama_proyek = ?, lokasi = ?, tanggal_mulai = ?, tanggal_selesai = ?, 
                    anggaran = ?, status = ?
                WHERE id_proyek = ?;
            """;
            PreparedStatement ps2 = conn.prepareStatement(updateSQL);
            ps2.setString(1, nama);
            ps2.setString(2, lokasi);
            ps2.setDate(3, java.sql.Date.valueOf(mulaiDate));
            ps2.setDate(4, java.sql.Date.valueOf(selesaiDate));
            ps2.setBigDecimal(5, new java.math.BigDecimal(anggaranStr));
            ps2.setString(6, status);
            ps2.setString(7, idProyek);

            int rows = ps2.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, 
                    "Proyek berhasil diperbarui!", 
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);

                Menampilkan_Proyek tampilFrame = new Menampilkan_Proyek(loggedInUsername);
                tampilFrame.setLocationRelativeTo(null);
                tampilFrame.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Gagal memperbarui proyek. Pastikan data proyek tersedia!", 
                    "Gagal", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, 
                "Kesalahan database: " + e.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, 
                "Anggaran harus berupa angka!", 
                "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new KP_1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
