/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.JOptionPane;

public class KP_6 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KP_6.class.getName());
    private String loggedInUsername;

    public KP_6() {
        initComponents();
        setLocationRelativeTo(null);
        setKategoriOptions();
    }

    public KP_6(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        System.out.println("DEBUG: Kontraktor di KP_6 = " + loggedInUsername);
        setKategoriOptions();
    }

    // ✅ Tambahkan opsi “Lainnya”
    private void setKategoriOptions() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Material");
        jComboBox1.addItem("Upah");
        jComboBox1.addItem("Transportasi");
        jComboBox1.addItem("Sewa Alat");
        jComboBox1.addItem("Lainnya");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField5 = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel11.setText("Kategori Baru");
        jLabel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 200, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel10.setText("Keterangan Baru");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 250, 210, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel9.setText("Jumlah Baru");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 200, -1));

        jLabel8.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel8.setText("Tanggal Baru (yyyy-mm-dd)");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 200, -1));

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UPDATE PENGELUARAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 470, 50));

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kirim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 83, -1));

        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 83, -1));

        jTextField7.setBackground(new java.awt.Color(0, 0, 102));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 210, 30));

        jFormattedTextField2.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, 200, 30));

        jFormattedTextField4.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 200, 30));

        jFormattedTextField5.setBackground(new java.awt.Color(0, 0, 102));
        jFormattedTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jFormattedTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jFormattedTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 200, 30));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setText("ID Pengeluaran");
        jLabel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFormattedTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField2ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Tombol "Kembali" → buka Kelola_Pengeluaran
        Kelola_Pengeluaran kembaliFrame = new Kelola_Pengeluaran(loggedInUsername);
        kembaliFrame.setLocationRelativeTo(null);
        kembaliFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Tombol "Kirim" → update pengeluaran terakhir proyek kontraktor
        String idPengeluaran = jFormattedTextField5.getText().trim();
        String tanggalStr = jFormattedTextField4.getText().trim();
        String jumlahStr = jFormattedTextField2.getText().trim();
        String kategori = (String) jComboBox1.getSelectedItem();
        String keterangan = jTextField7.getText().trim();

        if (idPengeluaran.isEmpty() || tanggalStr.isEmpty() || jumlahStr.isEmpty() || kategori == null || keterangan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = db_connection.getConnection()) {
            String getProyek = "SELECT Proyek_id_proyek FROM pengguna WHERE username = ?";
            PreparedStatement psProyek = conn.prepareStatement(getProyek);
            psProyek.setString(1, loggedInUsername);
            ResultSet rs = psProyek.executeQuery();

            if (!rs.next() || rs.getString("Proyek_id_proyek") == null) {
                JOptionPane.showMessageDialog(this, "Kontraktor belum memiliki proyek!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String proyekId = rs.getString("Proyek_id_proyek");

            String cekId = "SELECT id_pengeluaran FROM pengeluaran WHERE id_pengeluaran = ? AND Proyek_id_proyek = ?";
            PreparedStatement psCek = conn.prepareStatement(cekId);
            psCek.setString(1, idPengeluaran);
            psCek.setString(2, proyekId);
            ResultSet rsCek = psCek.executeQuery();

            if (!rsCek.next()) {
                JOptionPane.showMessageDialog(this, "ID Pengeluaran tidak valid untuk proyek Anda!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd");
            java.time.LocalDate tanggalValid;
            try {
                tanggalValid = java.time.LocalDate.parse(tanggalStr, formatter);
            } catch (java.time.format.DateTimeParseException e) {
                JOptionPane.showMessageDialog(this, "Format tanggal harus yyyy-mm-dd dan valid!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.math.BigDecimal jumlah;
            try {
                jumlah = new java.math.BigDecimal(jumlahStr.replace(",", "").replace(".", ""));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka valid!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            String updateSQL = """
                UPDATE pengeluaran 
                SET tanggal_pengeluaran = ?, jumlah = ?, kategori = ?, keterangan = ?
                WHERE id_pengeluaran = ? AND Proyek_id_proyek = ?;
            """;
            PreparedStatement stmt = conn.prepareStatement(updateSQL);
            stmt.setDate(1, java.sql.Date.valueOf(tanggalValid));
            stmt.setBigDecimal(2, jumlah);
            stmt.setString(3, kategori);
            stmt.setString(4, keterangan);
            stmt.setString(5, idPengeluaran);
            stmt.setString(6, proyekId);

            int affected = stmt.executeUpdate();

            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "Pengeluaran berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                Menampilkan_Pengeluaran tampilFrame = new Menampilkan_Pengeluaran(loggedInUsername, idPengeluaran);
                tampilFrame.setLocationRelativeTo(null);
                tampilFrame.setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Update gagal, periksa kembali input Anda.", "Gagal", JOptionPane.WARNING_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan Database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jFormattedTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField4ActionPerformed

    private void jFormattedTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new KP_6().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
