/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

public class KPA_3 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KPA_3.class.getName());
    private String loggedInUsername;

    public KPA_3() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultTableModel();
    }

    public KPA_3(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        System.out.println("DEBUG: Admin login di KPA_3 = " + loggedInUsername);
        setDefaultTableModel();

        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                loadExpenseData();
                return null;
            }
        }.execute();
    }

    private String formatRupiah(double amount) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,###", symbols);
        return "Rp " + df.format(amount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIHAT PENGELUARAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 470, 60));

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 83, -1));

        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 83, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 790, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola admin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 804, 453));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // Tombol "Kembali" ke Menu_Admin
        Menu_Admin menuFrame = new Menu_Admin(loggedInUsername);
        menuFrame.setLocationRelativeTo(null);
        menuFrame.setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Tombol "Refresh"
        loadExpenseData();
    }//GEN-LAST:event_jButton2ActionPerformed

    // ✅ Set tabel default kosong
    private void setDefaultTableModel() {
        jTable1.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID Pengeluaran", "Tanggal", "Keterangan", "Jumlah (Rp)", "Kategori"}
        ));
    }

    // ✅ Fungsi untuk load data pengeluaran dari database
    private void loadExpenseData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Pengeluaran");
        model.addColumn("Tanggal Pengeluaran");
        model.addColumn("Keterangan");
        model.addColumn("Jumlah (Rp)");
        model.addColumn("Kategori");

        try (Connection conn = db_connection.getConnection()) {
            String query = """
                SELECT pg.id_pengeluaran, pg.tanggal_pengeluaran, pg.keterangan, pg.jumlah, pg.kategori
                FROM pengeluaran pg
                INNER JOIN proyek pr ON pg.Proyek_id_proyek = pr.id_proyek
                INNER JOIN pengguna p ON pr.id_proyek = p.Proyek_id_proyek
                WHERE p.username = ?;
            """;

            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, loggedInUsername);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                // ✅ Format jumlah ke Rupiah
                double jumlah = rs.getDouble("jumlah");
                String formattedJumlah = formatRupiah(jumlah);

                model.addRow(new Object[]{
                    rs.getString("id_pengeluaran"),
                    rs.getDate("tanggal_pengeluaran"),
                    rs.getString("keterangan"),
                    formattedJumlah,
                    rs.getString("kategori")
                });
            }

            // ✅ Update tampilan tabel di UI
            SwingUtilities.invokeLater(() -> jTable1.setModel(model));

            if (model.getRowCount() == 0) {
                SwingUtilities.invokeLater(() ->
                    JOptionPane.showMessageDialog(this, "Tidak ada data pengeluaran ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE)
                );
            }

        } catch (SQLException ex) {
            SwingUtilities.invokeLater(() ->
                JOptionPane.showMessageDialog(this, "Gagal memuat data pengeluaran: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE)
            );
            ex.printStackTrace();
        }
    }

    // Main Method
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new KPA_3().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
