/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Frame: KPA_9.java
 * Fungsi: Menghapus laporan proyek yang hanya dimiliki oleh admin login
 * Setelah berhasil → kembali ke halaman lihat laporan (KPA_7)
 * @author hp
 */
public class KPA_9 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KPA_9.class.getName());
    private String loggedInUsername;

    public KPA_9() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public KPA_9(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        System.out.println("DEBUG: Admin login di KPA_9 = " + loggedInUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jFrame1 = new javax.swing.JFrame();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HAPUS LAPORAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 330, 60));

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kirim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 83, -1));

        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 83, -1));

        jTextField1.setBackground(new java.awt.Color(0, 0, 102));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 400, 50));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("Masukkan ID LAPORAN");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola admin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // ✅ Tombol "Kembali"
        KelolaLaporanAdmin kelolaFrame = new KelolaLaporanAdmin(loggedInUsername);
        kelolaFrame.setLocationRelativeTo(null);
        kelolaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // ✅ Tombol "Kirim" (Hapus laporan berdasarkan ID)                                        
        String idLaporan = jTextField1.getText().trim();

        if (idLaporan.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Masukkan ID laporan yang ingin dihapus.", 
                "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = db_connection.getConnection()) {
            // 🔹 Langkah 1: Ambil proyek admin login
            String getProyekSQL = "SELECT Proyek_id_proyek FROM pengguna WHERE username = ?";
            PreparedStatement psProyek = conn.prepareStatement(getProyekSQL);
            psProyek.setString(1, loggedInUsername);
            ResultSet rsProyek = psProyek.executeQuery();

            if (!rsProyek.next() || rsProyek.getString("Proyek_id_proyek") == null) {
                JOptionPane.showMessageDialog(this, 
                    "Admin belum memiliki proyek.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String proyekId = rsProyek.getString("Proyek_id_proyek");

            // 🔹 Langkah 2: Ambil detail laporan
            String getLaporanSQL = """
                SELECT id_laporan, tanggal_laporan, jenis_kendala, status_tindak_lanjut
                FROM laporan 
                WHERE id_laporan = ? AND Proyek_id_proyek = ?;
            """;
            PreparedStatement psLaporan = conn.prepareStatement(getLaporanSQL);
            psLaporan.setString(1, idLaporan);
            psLaporan.setString(2, proyekId);
            ResultSet rsLaporan = psLaporan.executeQuery();

            if (!rsLaporan.next()) {
                JOptionPane.showMessageDialog(this, 
                    "Laporan tidak ditemukan atau bukan milik proyek Anda.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 🔹 Simpan detail laporan untuk ditampilkan di popup
            String tanggal = rsLaporan.getString("tanggal_laporan");
            String jenis = rsLaporan.getString("jenis_kendala");
            String status = rsLaporan.getString("status_tindak_lanjut");

            // 🔹 Langkah 3: Konfirmasi penghapusan
            String pesanKonfirmasi = String.format("""
                Apakah Anda yakin ingin menghapus laporan berikut?

                ID Laporan     : %s
                Tanggal        : %s
                Jenis Kendala  : %s
                Status         : %s

                ⚠️ Tindakan ini tidak dapat dibatalkan.
                """, idLaporan, tanggal, jenis, status);

            int konfirmasi = JOptionPane.showConfirmDialog(
                this,
                pesanKonfirmasi,
                "Konfirmasi Penghapusan",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.ERROR_MESSAGE
            );

            if (konfirmasi != JOptionPane.YES_OPTION) {
                JOptionPane.showMessageDialog(this, 
                    "Penghapusan laporan dibatalkan.", 
                    "Dibatalkan", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // 🔹 Langkah 4: Hapus laporan
            String deleteSQL = "DELETE FROM laporan WHERE id_laporan = ? AND Proyek_id_proyek = ?";
            PreparedStatement stmt = conn.prepareStatement(deleteSQL);
            stmt.setString(1, idLaporan);
            stmt.setString(2, proyekId);

            int rows = stmt.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(this, 
                    "✅ Laporan berhasil dihapus!", 
                    "Sukses", JOptionPane.INFORMATION_MESSAGE);
                KPA_7 lihatLaporanFrame = new KPA_7(loggedInUsername);
                lihatLaporanFrame.setLocationRelativeTo(null);
                lihatLaporanFrame.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, 
                    "Gagal menghapus laporan.", 
                    "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, 
                "Kesalahan Database: " + ex.getMessage(), 
                "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new KPA_9().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
