/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 * Frame: KPA_7.java
 * Fungsi: Menampilkan laporan proyek milik admin login
 * Admin hanya bisa melihat laporan dari proyek yang dia kelola
 * Tombol: Refresh dan Kembali
 * @author hp
 */
public class KPA_7 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KPA_7.class.getName());
    
    // ✅ Variabel untuk menyimpan username admin yang login
    private String loggedInUsername;

    public KPA_7() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultTableModel();
    }

    public KPA_7(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        System.out.println("DEBUG: Admin login di KPA_7 = " + loggedInUsername);
        setDefaultTableModel();
        loadLaporanData(); // otomatis load data laporan saat dibuka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIHAT LAPORAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 310, 60));

        jButton3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, 83, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 780, 260));

        jButton4.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 83, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // ✅ Tombol "Kembali"
        KelolaLaporanAdmin kelolaFrame = new KelolaLaporanAdmin(loggedInUsername);
        kelolaFrame.setLocationRelativeTo(null);
        kelolaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            // ✅ Tombol "Refresh"                                        
        loadLaporanData(); // panggil ulang data laporan
    }//GEN-LAST:event_jButton4ActionPerformed

    // ✅ Model tabel default (untuk NetBeans Preview)
    private void setDefaultTableModel() {
        jTable1.setModel(new DefaultTableModel(
            new Object[][] {},
            new String[] {
                "ID Laporan", "Tanggal Laporan", "Jenis Kendala", "Deskripsi", "Status Tindak Lanjut", "Proyek ID"
            }
        ));
    }

    // ✅ Memuat data laporan khusus proyek milik admin login
    private void loadLaporanData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan");
        model.addColumn("Tanggal Laporan");
        model.addColumn("Jenis Kendala");
        model.addColumn("Deskripsi");
        model.addColumn("Status Tindak Lanjut");
        model.addColumn("Proyek ID");

        try (Connection conn = db_connection.getConnection()) {
            // 🔹 Langkah 1: Ambil proyek milik admin login
            String proyekSQL = "SELECT Proyek_id_proyek FROM pengguna WHERE username = ?";
            PreparedStatement psProyek = conn.prepareStatement(proyekSQL);
            psProyek.setString(1, loggedInUsername);
            ResultSet rsProyek = psProyek.executeQuery();

            if (!rsProyek.next() || rsProyek.getString("Proyek_id_proyek") == null) {
                JOptionPane.showMessageDialog(this, "Admin belum memiliki proyek terdaftar.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                jTable1.setModel(model);
                return;
            }

            String proyekId = rsProyek.getString("Proyek_id_proyek");

            // 🔹 Langkah 2: Ambil laporan berdasarkan proyek admin login
            String laporanSQL = """
                SELECT id_laporan, tanggal_laporan, jenis_kendala, deskripsi, 
                       status_tindak_lanjut, Proyek_id_proyek
                FROM laporan 
                WHERE Proyek_id_proyek = ?
                ORDER BY tanggal_laporan DESC;
            """;

            PreparedStatement stmt = conn.prepareStatement(laporanSQL);
            stmt.setString(1, proyekId);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_laporan"),
                    rs.getDate("tanggal_laporan"),
                    rs.getString("jenis_kendala"),
                    rs.getString("deskripsi"),
                    rs.getString("status_tindak_lanjut"),
                    rs.getString("Proyek_id_proyek")
                });
            }

            jTable1.setModel(model);

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Belum ada laporan untuk proyek Anda.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data laporan: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    // ⚙️ Main method
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new KPA_7().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
