/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 * Frame: KPA_8.java
 * Fungsi: Update laporan proyek (hanya milik admin login)
 * Setelah berhasil update → otomatis menuju KPA_7.java
 * @author hp
 */
public class KPA_8 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KPA_8.class.getName());
    private String loggedInUsername;

    public KPA_8() {
        initComponents();
        setLocationRelativeTo(null);
        isiComboBoxStatus();
    }

    public KPA_8(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        isiComboBoxStatus();
        System.out.println("DEBUG: Admin login di KPA_8 = " + loggedInUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel4.setText("Status Laporan");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 200, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel3.setText("ID Laporan");
        jLabel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 200, -1));

        jTextField4.setBackground(new java.awt.Color(0, 0, 102));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 200, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 200, 30));

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("UPDATE LAPORAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 470, 60));

        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kirim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 83, -1));

        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Kembali");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 83, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola admin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 799, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

        // ✅ Inisialisasi isi ComboBox hanya sekali
    private void isiComboBoxStatus() {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Tahap Perancangan");
        jComboBox1.addItem("Sedang Dikerjakan");
        jComboBox1.addItem("Tertunda");
        jComboBox1.addItem("Sudah Selesai");
        jComboBox1.addItem("Dibatalkan");
    }
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // ✅ Tombol "Kembali"
        KelolaLaporanAdmin kelolaFrame = new KelolaLaporanAdmin(loggedInUsername);
        kelolaFrame.setLocationRelativeTo(null);
        kelolaFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            // ✅ Tombol "Kirim" (UPDATE laporan)
        String idLaporan = jTextField4.getText().trim();
        String statusBaru = (String) jComboBox1.getSelectedItem();

        if (idLaporan.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID laporan terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try (Connection conn = db_connection.getConnection()) {
            // 🔹 Langkah 1: Ambil proyek admin login
            String getProyekSQL = "SELECT Proyek_id_proyek FROM pengguna WHERE username = ?";
            PreparedStatement psProyek = conn.prepareStatement(getProyekSQL);
            psProyek.setString(1, loggedInUsername);
            ResultSet rsProyek = psProyek.executeQuery();

            if (!rsProyek.next() || rsProyek.getString("Proyek_id_proyek") == null) {
                JOptionPane.showMessageDialog(this, "Admin belum memiliki proyek.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String proyekId = rsProyek.getString("Proyek_id_proyek");

            // 🔹 Langkah 2: Cek apakah laporan tersebut milik proyek admin login
            String cekSQL = "SELECT id_laporan FROM laporan WHERE id_laporan = ? AND Proyek_id_proyek = ?";
            PreparedStatement psCek = conn.prepareStatement(cekSQL);
            psCek.setString(1, idLaporan);
            psCek.setString(2, proyekId);
            ResultSet rsCek = psCek.executeQuery();

            if (!rsCek.next()) {
                JOptionPane.showMessageDialog(this, "Laporan tidak ditemukan atau bukan milik proyek Anda.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // 🔹 Langkah 3: Update status laporan
            String updateSQL = "UPDATE laporan SET status_tindak_lanjut = ? WHERE id_laporan = ? AND Proyek_id_proyek = ?";
            PreparedStatement stmt = conn.prepareStatement(updateSQL);
            stmt.setString(1, statusBaru);
            stmt.setString(2, idLaporan);
            stmt.setString(3, proyekId);

            int affected = stmt.executeUpdate();

            if (affected > 0) {
                JOptionPane.showMessageDialog(this, "Status laporan berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                KPA_7 lihatFrame = new KPA_7(loggedInUsername);
                lihatFrame.setLocationRelativeTo(null);
                lihatFrame.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui status laporan.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Kesalahan Database: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new KPA_8().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
