/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class KPA_5 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KPA_5.class.getName());
    private String loggedInUsername; // simpan admin yang login

    // Konstruktor default (untuk preview NetBeans)
    public KPA_5() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultTableModel();
    }

    // Konstruktor dengan username admin login
    public KPA_5(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        System.out.println("DEBUG: Admin login di KPA_5 = " + loggedInUsername);
        setDefaultTableModel();

        // 🔥 Auto-load data di background biar gak freeze
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                loadProgressData();
                return null;
            }
        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LIHAT PROGRES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 470, 60));

        jButton4.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 0, 0));
        jButton4.setText("Refresh");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 83, -1));

        jButton3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 460, 83, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 790, 250));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola admin.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 797, 492));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
                // 🔁 Refresh data
        new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() {
                loadProgressData();
                return null;
            }
        }.execute();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                // ⬅️ Kembali ke Menu Admin
        Menu_Admin menuFrame = new Menu_Admin(loggedInUsername);
        menuFrame.setLocationRelativeTo(null);
        menuFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

        // Model tabel kosong awal
    private void setDefaultTableModel() {
        jTable1.setModel(new DefaultTableModel(
            new Object[][]{},
            new String[]{"ID Progres", "Nama Proyek", "Tanggal Update", "Persentase (%)", "Deskripsi"}
        ));
    }

    // ✅ Fungsi untuk load data progres dari database
    private void loadProgressData() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Progres");
        model.addColumn("Nama Proyek");
        model.addColumn("Tanggal Update");
        model.addColumn("Persentase (%)");
        model.addColumn("Deskripsi");

        try (Connection conn = db_connection.getConnection()) {
            // 🔥 Query disesuaikan dengan tabel "progres"
            String query = """
                SELECT prg.id_progres, pr.nama_proyek, prg.tanggal_update, prg.persentase_selesai, prg.deskripsi
                FROM progres prg
                INNER JOIN proyek pr ON prg.Proyek_id_proyek = pr.id_proyek
                INNER JOIN pengguna p ON pr.id_proyek = p.Proyek_id_proyek
                WHERE p.username = ?;
            """;

            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, loggedInUsername);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_progres"),
                    rs.getString("nama_proyek"),
                    rs.getDate("tanggal_update"),
                    rs.getDouble("persentase_selesai"),
                    rs.getString("deskripsi")
                });
            }

            SwingUtilities.invokeLater(() -> jTable1.setModel(model));

            if (model.getRowCount() == 0) {
                SwingUtilities.invokeLater(() ->
                    JOptionPane.showMessageDialog(this, "Tidak ada data progres ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE)
                );
            }

        } catch (SQLException ex) {
            SwingUtilities.invokeLater(() ->
                JOptionPane.showMessageDialog(this, "Gagal memuat data progres: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE)
            );
            ex.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    // Main method
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new KPA_5().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
