/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Frame: Menampilkan_Laporan.java
 * Fungsi: Menampilkan laporan milik kontraktor login
 * Tambahan: Highlight otomatis laporan terakhir yang ditambahkan
 * @author hp
 */
public class Menampilkan_Laporan extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menampilkan_Laporan.class.getName());

    // ✅ Simpan username kontraktor yang login
    private String loggedInUsername;

    // ✅ Simpan ID laporan terakhir yang ingin di-highlight
    private String highlightedId;

    /**
     * Konstruktor default (untuk preview)
     */
    public Menampilkan_Laporan() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * ✅ Konstruktor saat dibuka dari menu (tanpa highlight)
     */
    public Menampilkan_Laporan(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        loadLaporanData(null);
    }

    /**
     * ✅ Konstruktor saat dibuka setelah tambah laporan (dengan highlight)
     */
    public Menampilkan_Laporan(String username, String highlightId) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        this.highlightedId = highlightId;
        loadLaporanData(highlightId);
    }

    /**
     * ✅ Fungsi untuk memuat laporan dari proyek kontraktor login + highlight
     */
    private void loadLaporanData(String highlightId) {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("ID Laporan");
        model.addColumn("Tanggal Laporan");
        model.addColumn("Jenis Kendala");
        model.addColumn("Deskripsi");
        model.addColumn("Status Tindak Lanjut");

        try (Connection conn = db_connection.getConnection()) {
            String query = """
                SELECT l.id_laporan, l.tanggal_laporan, l.jenis_kendala, l.deskripsi, l.status_tindak_lanjut
                FROM laporan l
                JOIN pengguna u ON l.Proyek_id_proyek = u.Proyek_id_proyek
                WHERE u.username = ?
                ORDER BY l.tanggal_laporan DESC;
            """;

            PreparedStatement stmt = conn.prepareStatement(query);
            stmt.setString(1, loggedInUsername);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id_laporan"),
                    rs.getDate("tanggal_laporan"),
                    rs.getString("jenis_kendala"),
                    rs.getString("deskripsi"),
                    rs.getString("status_tindak_lanjut")
                });
            }

            jTable1.setModel(model);

            // ✅ Highlight otomatis baris laporan terbaru (jika ada)
            if (highlightId != null) {
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    String id = jTable1.getValueAt(i, 0).toString();
                    if (highlightId.equalsIgnoreCase(id)) {
                        jTable1.setRowSelectionInterval(i, i);
                        jTable1.scrollRectToVisible(jTable1.getCellRect(i, 0, true));
                        break;
                    }
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data laporan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LIHAT LAPORAN ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 550, 50));

        jButton2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Refresh");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 83, -1));

        jButton3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 83, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 790, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Tombol "Refresh"
        loadLaporanData(highlightedId);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Tombol "Kembali"
        Kelola_Laporan laporanFrame = new Kelola_Laporan(loggedInUsername);
        laporanFrame.setLocationRelativeTo(null);
        laporanFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Menampilkan_Laporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
