/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;

/**
 * Frame: Menampilkan_Pengeluaran.java
 * Fungsi: Menampilkan seluruh data pengeluaran proyek milik kontraktor yang sedang login
 * + Auto refresh dan highlight ID pengeluaran terakhir ditambah/diupdate
 * + Format jumlah ke dalam bentuk Rp 1.000.000
 * @author hp
 */
public class Menampilkan_Pengeluaran extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menampilkan_Pengeluaran.class.getName());
    
    private String loggedInUsername;
    private String highlightedId;

    public Menampilkan_Pengeluaran() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Menampilkan_Pengeluaran(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        loadData(null);
    }

    public Menampilkan_Pengeluaran(String username, String highlightId) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        this.highlightedId = highlightId;
        loadData(highlightId);
    }

    // ✅ Format angka menjadi Rupiah
    private String formatRupiah(double amount) {
        DecimalFormatSymbols symbols = new DecimalFormatSymbols();
        symbols.setGroupingSeparator('.');
        DecimalFormat df = new DecimalFormat("#,###", symbols);
        return "Rp " + df.format(amount);
    }

    // ✅ Tampilkan data pengeluaran
    private void loadData(String highlightId) {
        DefaultTableModel model = new DefaultTableModel(
            new String[]{"ID Pengeluaran", "Tanggal Pengeluaran", "Jumlah", "Kategori", "Keterangan"}, 0
        );

        try (Connection conn = db_connection.getConnection()) {
            String sql = """
                SELECT p.id_pengeluaran, p.tanggal_pengeluaran, p.jumlah, p.kategori, p.keterangan
                FROM pengeluaran p
                JOIN pengguna u ON p.Proyek_id_proyek = u.Proyek_id_proyek
                WHERE u.username = ?
                ORDER BY p.tanggal_pengeluaran DESC;
            """;
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, loggedInUsername);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                double jumlah = rs.getDouble("jumlah");
                String jumlahFormatted = formatRupiah(jumlah);

                model.addRow(new Object[]{
                    rs.getString("id_pengeluaran"),
                    rs.getDate("tanggal_pengeluaran"),
                    jumlahFormatted,
                    rs.getString("kategori"),
                    rs.getString("keterangan")
                });
            }

            jTable1.setModel(model);

            // ✅ Highlight baris terakhir yang diubah
            if (highlightId != null) {
                for (int i = 0; i < jTable1.getRowCount(); i++) {
                    String id = jTable1.getValueAt(i, 0).toString();
                    if (id.equalsIgnoreCase(highlightId)) {
                        jTable1.setRowSelectionInterval(i, i);
                        jTable1.scrollRectToVisible(jTable1.getCellRect(i, 0, true));
                        break;
                    }
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Kesalahan Database: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LIHAT PENGELUARAN");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 470, 50));

        jButton3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 83, -1));

        jButton2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 83, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 790, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 797, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Tombol "Kembali" ke Kelola_Pengeluaran
        Kelola_Pengeluaran kembaliFrame = new Kelola_Pengeluaran(loggedInUsername);
        kembaliFrame.setLocationRelativeTo(null);
        kembaliFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Tombol "Refresh"
        loadData(highlightedId);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Menampilkan_Pengeluaran().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
