package GUI;

import db_connector.db_connection;
import java.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class Nampilkan_Progres extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nampilkan_Progres.class.getName());
    
    private String loggedInUsername;
    private String highlightedId; // ID progres yang baru ditambah / diupdate

    public Nampilkan_Progres() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public Nampilkan_Progres(String username) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        loadProgresData(null);
    }

    public Nampilkan_Progres(String username, String highlightId) {
        initComponents();
        setLocationRelativeTo(null);
        this.loggedInUsername = username;
        this.highlightedId = highlightId;
        loadProgresData(highlightId);
    }

private void loadProgresData(String highlightId) {
    DefaultTableModel model = new DefaultTableModel(
        new String[]{"ID Progres", "Tanggal Progres", "Persentase Selesai", "Deskripsi"}, 0
    );

    try (Connection conn = db_connection.getConnection()) {
        String query = """
            SELECT p.id_progres, p.tanggal_update, p.persentase_selesai, p.deskripsi
            FROM progres p
            JOIN pengguna u ON p.Proyek_id_proyek = u.Proyek_id_proyek
            WHERE u.username = ?
            ORDER BY p.tanggal_update DESC;
        """;

        // ✅ Tambahkan baris ini
        PreparedStatement stmt = conn.prepareStatement(query);
        stmt.setString(1, loggedInUsername);
        ResultSet rs = stmt.executeQuery();

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getString("id_progres"),
                rs.getDate("tanggal_update"),
                rs.getBigDecimal("persentase_selesai"), // DECIMAL(5,2)
                rs.getString("deskripsi")
            });
        }

        jTable1.setModel(model);

        // ✅ Highlight ID yang baru ditambah/diupdate
        if (highlightId != null) {
            for (int i = 0; i < jTable1.getRowCount(); i++) {
                if (highlightId.equalsIgnoreCase(jTable1.getValueAt(i, 0).toString())) {
                    jTable1.setRowSelectionInterval(i, i);
                    jTable1.scrollRectToVisible(jTable1.getCellRect(i, 0, true));
                    break;
                }
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal memuat data progres: " + e.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Javanese Text", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("LIHAT PROGRES");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 340, 60));

        jButton3.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 83, -1));

        jButton2.setFont(new java.awt.Font("Corbel", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 0));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 83, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 790, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/kelola kontraktor.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 799, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Tombol "Refresh" → reload data progres
        loadProgresData(highlightedId);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Tombol "Kembali" → kembali ke Menampilkan_Progres
        Menampilkan_Progres kembaliFrame = new Menampilkan_Progres(loggedInUsername);
        kembaliFrame.setLocationRelativeTo(null);
        kembaliFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new Nampilkan_Progres().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
